#!/bin/sh

echo "   * install vundle"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "   * ~/.vim"
mkdir ~/.vim

echo "   * .vimrc"
cp ./vim/vimrc ~/.vimrc

echo " installing theme"
mkdir ~/.vim/colors
cp ./vim/colors/monokai.vim ~/.vim/colors/

ls ~/.vim
