#!/bin/sh

echo "   * install vundle"
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

echo "   * ~/.vim"
mkdir ~/.vim

echo "   * .vimrc"
cp ./vim/vimrc ~/.vimrc

ls ~/.vim
