#!/bin/sh

echo "   * install vundle"
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

echo "   * ~/.vim"
mkdir ~/.vim

echo "   * .vimrc"
cp ./vim/vimrc ~/.vimrc

echo " installing theme"
mkdir ~/.vim/colors
cp ./vim/colors/monokai.vim ~/.vim/colors/

ls ~/.vim
