#!/bin/sh

echo ""
echo " *** setting up zsh *** "
echo "     ⚠️  this overrides ~/.zshrc *** "
echo ""
./scripts/setup_zsh


echo ""
echo " *** setting up vim configs *** "
echo ""
./scripts/setup_vim

echo ""
echo " *** setting up tmux configs *** "
echo ""
./scripts/setup_tmux

echo ""
echo " *** setting up yubikey *** "
echo ""
./scripts/setup_yubi
